### ISSUE TITLE
Phoenix HTML generated epub?

### ISSUE THREAD

**Issue by niccolox** [milmazz/bupe#22]
any thoughts or examples of using this package to create epub from phoenix generated pages / routes?

**Comment by milmazz** [comment]
@niccolox You can use `ex_doc` for that for example, `ex_doc` supports an `epub` formatter option. Sorry for the late response.

**Comment by milmazz** [comment]
Please let me know if you still want to use `bupe` directly, I can add some examples if you want, but as I said earlier and based on your scenario, I think `ex_doc` is your best choice here.

**Comment by niccolox** [comment]
thanks
